[package]
name = "akira"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.8.2"
scarb-version = "2.8.2"

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.16.0" }

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy= "avoid"

[scripts]
test = "snforge test"
