[package]
name = "akira_smart_contract"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.0"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", branch = "main" }
cubit = {git = "https://github.com/influenceth/cubit.git"}

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
casm = true